In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import backtrader as bt
import datetime

In [43]:
#df = pd.read_csv("../raw_data/merged_data_THETAModel.csv")
#df.dropna(inplace=True)
#df

In [54]:
df = pd.read_csv("../raw_data/arima_merged_data_model.csv")
df.dropna(inplace=True)
df

,Unnamed: 0,timestamp,open,high,low,close,volat_ATR,predictions
0,0,2023-01-02,16610.4,16799.0,16541.2,16666.0,348.494688,16610.3
1,1,2023-01-03,16665.9,16774.0,16600.3,16667.2,336.009353,16666.0
2,2,2023-01-04,16667.3,16984.6,16645.7,16842.1,336.215828,16667.2
3,3,2023-01-05,16842.2,16872.8,16740.4,16823.8,321.657555,16842.1
4,4,2023-01-06,16823.8,17030.0,16664.8,16943.8,324.767729,16823.8
...,...,...,...,...,...,...,...,...
148,148,2023-05-30,27722.1,28038.6,27530.0,27680.1,854.472960,27722.0
149,149,2023-05-31,27680.0,27825.0,26826.0,27201.1,864.796320,27680.1
150,150,2023-06-01,27201.1,27347.9,26600.0,26805.3,856.446583,27201.1
151,151,2023-06-02,26805.3,27290.0,26477.6,27227.8,853.300398,26805.3
152,152,2023-06-03,27227.8,27340.2,26900.0,27054.9,823.793227,27227.8

In [55]:
#df = pd.read_csv("../raw_data/final_merged_data_ETS_model.csv")
#df.dropna(inplace=True)
#df.head(20)

In [56]:
column_names = df.columns.tolist()
column_names

['Unnamed: 0',
 'timestamp',
 'open',
 'high',
 'low',
 'close',
 'volat_ATR',
 'predictions']

In [57]:
#prediction = 2

In [58]:
solutions = []

In [59]:
imput = 1000

In [60]:
#for index, row in df.iterrows():
 #   close_val = row["close"]
  #  if close_val > prediction == True:
   #     test.append(1)

In [61]:
for index, row in df.iterrows():
    close_value = row['close']
    prediction_value = row['predictions']
    volat_atr = row["volat_ATR"]
    high_value = row["high"]
    low_value = row["low"]
    open_value = row["open"]
    time_stamp = row["timestamp"]
    short_stop = volat_atr + open_value
    long_stop = open_value - volat_atr
    tp_mult = 0.002
    
    if open_value > prediction_value:
        
        if open_value - (open_value * tp_mult) >= low_value:
            winn = (imput*0.9994) * (1 + tp_mult)
            imput = winn
            solutions.append(f"Enter short trade, cut off take profit {time_stamp}, {imput}")
        elif short_stop <= high_value:
            loss = (imput*0.9994)*(1-((volat_atr / open_value)/100))
            imput = loss
            solutions.append(f"Enter short trade, cut off at short stop level {time_stamp}, {imput}")
        else:
            take_profit = (close_value / prediction_value) * (imput*0.9994)
            imput = take_profit
            solutions.append(f"Enter short trade {time_stamp}, {imput}")
        
    elif open_value < prediction_value:
        
        if open_value + (open_value * tp_mult) <= high_value:
            winn = (imput*0.9994) * (1 + tp_mult)
            imput = winn
            solutions.append(f"Enter long trade, cut off take profit {time_stamp}, {imput}")
        elif long_stop >= low_value:
            loss = (imput*0.9994)*(1-((volat_atr / open_value)/100))
            imput = loss
            solutions.append(f"Enter long trade, cut off at long stop level {time_stamp}, {imput}")
        else:
            take_profit = (prediction_value / close_value) * (imput*0.9994)
            imput = take_profit
            solutions.append(f"Enter long trade {time_stamp}, {imput}")
            
    else:
        take_profit = 0
        imput = imput
        solutions.append("skip investment")

In [62]:
solutions

['Enter short trade, cut off take profit 2023-01-02, 1001.3987999999999',
 'Enter long trade, cut off take profit 2023-01-03, 1002.7995566414398',
 'Enter short trade 2023-01-04, 1012.714604892426',
 'Enter short trade, cut off take profit 2023-01-05, 1014.1311900817494',
 'skip investment',
 'Enter short trade, cut off take profit 2023-01-07, 1015.5497567904358',
 'skip investment',
 'Enter long trade, cut off take profit 2023-01-09, 1016.9703077902342',
 'Enter long trade, cut off take profit 2023-01-10, 1018.3928458567711',
 'skip investment',
 'Enter long trade, cut off take profit 2023-01-12, 1019.8173737695555',
 'Enter short trade, cut off take profit 2023-01-13, 1021.2438943119843',
 'Enter short trade, cut off take profit 2023-01-14, 1022.6724102713478',
 'skip investment',
 'skip investment',
 'Enter long trade, cut off take profit 2023-01-17, 1024.1029244388353',
 'Enter long trade, cut off take profit 2023-01-18, 1025.5354396095404',
 'Enter short trade 2023-01-19, 1044.1646290785436',
 'skip investment',
 'Enter long trade, cut off take profit 2023-01-21, 1045.6252065616986',
 'Enter long trade, cut off take profit 2023-01-22, 1047.087827100637',
 'Enter short trade, cut off take profit 2023-01-23, 1048.5524935531853',
 'Enter short trade, cut off take profit 2023-01-24, 1050.0192087811674',
 'Enter short trade, cut off take profit 2023-01-25, 1051.4879756504104',
 'skip investment',
 'skip investment',
 'Enter short trade, cut off take profit 2023-01-28, 1052.9587970307502',
 'Enter short trade, cut off take profit 2023-01-29, 1054.4316757960366',
 'Enter long trade, cut off take profit 2023-01-30, 1055.90661482414',
 'skip investment',
 'Enter short trade, cut off take profit 2023-02-01, 1057.3836169969559',
 'Enter short trade, cut off take profit 2023-02-02, 1058.8626852004113',
 'Enter long trade, cut off take profit 2023-02-03, 1060.3438223244696',
 'skip investment',
 'skip investment',
 'Enter short trade, cut off take profit 2023-02-06, 1061.827031263137',
 'Enter short trade 2023-02-07, 1083.4044332166523',
 'skip investment',
 'skip investment',
 'Enter long trade, cut off take profit 2023-02-10, 1084.9198993378357',
 'skip investment',
 'Enter long trade, cut off take profit 2023-02-12, 1086.4374852930293',
 'Enter long trade, cut off take profit 2023-02-13, 1087.957194047457',
 'Enter long trade, cut off take profit 2023-02-14, 1089.4790285704905',
 'skip investment',
 'Enter short trade, cut off take profit 2023-02-16, 1091.002991835655',
 'skip investment',
 'Enter long trade, cut off take profit 2023-02-18, 1092.5290868206346',
 'Enter long trade, cut off take profit 2023-02-19, 1094.0573165072792',
 'skip investment',
 'skip investment',
 'Enter long trade 2023-02-22, 1105.7094621285507',
 'skip investment',
 'Enter long trade, cut off take profit 2023-02-24, 1107.2561285241761',
 'Enter long trade 2023-02-25, 1107.997353221935',
 'skip investment',
 'Enter long trade, cut off take profit 2023-02-27, 1109.547219919622',
 'skip investment',
 'Enter short trade, cut off take profit 2023-03-01, 1111.0992545708455',
 'skip investment',
 'skip investment',
 'skip investment',
 'Enter short trade, cut off take profit 2023-03-05, 1112.653460208139',
 'Enter long trade, cut off take profit 2023-03-06, 1114.209839868278',
 'skip investment',
 'skip investment',
 'Enter long trade, cut off take profit 2023-03-09, 1115.7683965922859',
 'Enter short trade, cut off take profit 2023-03-10, 1117.329133425439',
 'skip investment',
 'skip investment',
 'skip investment',
 'skip investment',
 'skip investment',
 'Enter long trade, cut off take profit 2023-03-16, 1118.8920534172746',
 'Enter short trade, cut off take profit 2023-03-17, 1120.4571596215944',
 'Enter long trade, cut off take profit 2023-03-18, 1122.024455096473',
 'skip investment',
 'Enter short trade, cut off take profit 2023-03-20, 1123.5939429042621',
 'skip investment',
 'skip investment',
 'skip investment',
 'Enter long trade, cut off take profit 2023-03-24, 1125.1656261115966',
 'Enter short trade, cut off take profit 2023-03-25, 1126.7395077894014',
 'Enter long trade, cut off take profit 2023-03-26, 1128.3155910128971',
 'skip investment',
 'skip investment',
 'skip investment',
 'Enter short trade, cut off take profit 2023-03-30, 1129.893878861606',
 'skip investment',
 'Enter long trade, cut off take profit 2023-04-01, 1131.4743744193577',
 'Enter long trade, cut off take profit 2023-04-02, 1133.0570807742956',
 'Enter short trade, cut off take profit 2023-04-03, 1134.6420010188826',
 'skip investment',
 'Enter long trade, cut off take profit 2023-04-05, 1136.229138249908',
 'skip investment',
 'Enter short trade, cut off take profit 2023-04-07, 1137.818495568492',
 'skip investment',
 'skip investment',
 'skip investment',
 'skip investment',
 'skip investment',
 'Enter long trade, cut off take profit 2023-04-13, 1139.4100760800932',
 'skip investment',
 'Enter long trade, cut off take profit 2023-04-15, 1141.003882894514',
 'skip investment',
 'skip investment',
 'Enter short trade, cut off take profit 2023-04-18, 1142.5999191259068',
 'skip investment',
 'Enter long trade, cut off take profit 2023-04-20, 1144.19818789278',
 'skip investment',
 'Enter short trade, cut off take profit 2023-04-22, 1145.7986923180044',
 'skip investment',
 'Enter long trade, cut off take profit 2023-04-24, 1147.4014355288189',
 'Enter long trade, cut off take profit 2023-04-25, 1149.0064206568366',
 'skip investment',
 'Enter short trade, cut off at short stop level 2023-04-27, 1147.8374368701693',
 'skip investment',
 'skip investment',
 'skip investment',
 'skip investment',
 'Enter short trade, cut off take profit 2023-05-02, 1149.4430318768632',
 'Enter long trade, cut off take profit 2023-05-03, 1151.0508727898523',
 'skip investment',
 'skip investment',
 'skip investment',
 'Enter short trade, cut off take profit 2023-05-07, 1152.6609627507107',
 'Enter short trade, cut off take profit 2023-05-08, 1154.2733049054063',
 'skip investment',
 'skip investment',
 'Enter short trade, cut off take profit 2023-05-11, 1155.887902404308',
 'skip investment',
 'Enter short trade, cut off take profit 2023-05-13, 1157.5047584021913',
 'Enter short trade, cut off take profit 2023-05-14, 1159.1238760582444',
 'skip investment',
 'skip investment',
 'Enter long trade, cut off take profit 2023-05-17, 1160.7452585360747',
 'Enter long trade, cut off take profit 2023-05-18, 1162.368909003715',
 'Enter short trade, cut off take profit 2023-05-19, 1163.9948306336294',
 'skip investment',
 'Enter short trade, cut off take profit 2023-05-21, 1165.6230266027196',
 'skip investment',
 'skip investment',
 'skip investment',
 'Enter short trade, cut off take profit 2023-05-25, 1167.2535000923315',
 'Enter long trade, cut off take profit 2023-05-26, 1168.8862542882607',
 'Enter long trade, cut off take profit 2023-05-27, 1170.5212923807592',
 'skip investment',
 'Enter short trade, cut off take profit 2023-05-29, 1172.1586175645414',
 'Enter short trade, cut off take profit 2023-05-30, 1173.7982330387906',
 'Enter long trade, cut off take profit 2023-05-31, 1175.4401420071652',
 'skip investment',
 'skip investment',
 'skip investment']

In [41]:
print(f"Enter short trade {imput}")

Enter short trade 1175.4401420071652