In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import backtrader as bt
import datetime

In [76]:
#df = pd.read_csv("../raw_data/merged_data_THETAModel.csv")
#df.dropna(inplace=True)
#df

In [77]:
#df = pd.read_csv("../raw_data/arima_merged_data_model.csv")
#df.dropna(inplace=True)
#df

In [78]:
df = pd.read_csv("../raw_data/final_merged_data_ETS_model.csv")
df.dropna(inplace=True)
df.head(20)

,Unnamed: 0,timestamp,open,high,low,close,volat_ATR,predictions
0,0,2023-01-02,16610.4,16799.0,16541.2,16666.0,348.494688,16539.674162
1,1,2023-01-03,16665.9,16774.0,16600.3,16667.2,336.009353,16571.260964
2,2,2023-01-04,16667.3,16984.6,16645.7,16842.1,336.215828,16883.810018
3,3,2023-01-05,16842.2,16872.8,16740.4,16823.8,321.657555,16799.579425
4,4,2023-01-06,16823.8,17030.0,16664.8,16943.8,324.767729,16891.919807
5,5,2023-01-07,16943.9,16973.6,16900.1,16936.5,306.820034,16896.327002
6,6,2023-01-08,16936.5,17181.1,16905.0,17124.7,304.625746,16835.519674
7,7,2023-01-09,17124.6,17387.8,17098.2,17169.7,303.552479,17049.366082
8,8,2023-01-10,17169.6,17485.4,17140.4,17428.8,306.513016,17075.255404
9,9,2023-01-11,17428.8,18013.2,17306.4,17935.7,335.104943,17635.080411
10,10,2023-01-12,17935.6,19120.0,17902.4,18838.0,398.140305,17879.483807
11,11,2023-01-13,18838.1,19997.8,18711.0,19924.2,461.615997,18868.619963
12,12,2023-01-14,19924.3,21544.0,19882.6,20962.8,547.314854,19836.518585
13,13,2023-01-15,20962.8,21073.8,20556.0,20882.7,545.206651,20818.415782
14,14,2023-01-16,20882.7,21498.0,20606.6,21188.3,569.934747,20816.807219
15,15,2023-01-17,21188.2,21640.0,20827.8,21130.9,587.239408,21084.148630
16,16,2023-01-18,21130.8,21672.0,20386.0,20680.0,637.150879,21349.932934
17,17,2023-01-19,20680.1,21183.9,20659.9,21068.3,629.068673,20663.301703
18,18,2023-01-20,21068.3,22750.0,20856.4,22661.1,719.392339,21121.498332
19,19,2023-01-21,22661.0,23390.0,22422.0,22781.9,737.150029,22554.168636

In [79]:
column_names = df.columns.tolist()
column_names

['Unnamed: 0',
 'timestamp',
 'open',
 'high',
 'low',
 'close',
 'volat_ATR',
 'predictions']

In [80]:
#prediction = 2

In [81]:
solutions = []

In [82]:
imput = 1000

In [83]:
#for index, row in df.iterrows():
 #   close_val = row["close"]
  #  if close_val > prediction == True:
   #     test.append(1)

In [84]:
for index, row in df.iterrows():
    close_value = row['close']
    prediction_value = row['predictions']
    volat_atr = row["volat_ATR"]
    high_value = row["high"]
    low_value = row["low"]
    open_value = row["open"]
    time_stamp = row["timestamp"]
    short_stop = volat_atr + open_value
    long_stop = open_value - volat_atr
    tp_mult = 0.002
    
    if open_value > prediction_value:
        
        if open_value - (open_value * tp_mult) >= low_value:
            winn = (imput*0.9994) * (1 + tp_mult)
            imput = winn
            solutions.append(f"Enter short trade, cut off take profit {time_stamp}, {imput}")
        elif short_stop <= high_value:
            loss = (imput*0.9994)*(1-((volat_atr / open_value)))
            imput = loss
            solutions.append(f"Enter short trade, cut off at short stop level {time_stamp}, {imput}")
        else:
            take_profit = (close_value / prediction_value) * (imput*0.9994)
            imput = take_profit
            solutions.append(f"Enter short trade {time_stamp}, {imput}")
        
    elif open_value < prediction_value:
        
        if open_value + (open_value * tp_mult) <= high_value:
            winn = (imput*0.9994) * (1 + tp_mult)
            imput = winn
            solutions.append(f"Enter long trade, cut off take profit {time_stamp}, {imput}")
        elif long_stop >= low_value:
            loss = (imput*0.9994)*(1-((volat_atr / open_value)))
            imput = loss
            solutions.append(f"Enter long trade, cut off at long stop level {time_stamp}, {imput}")
        else:
            take_profit = (prediction_value / close_value) * (imput*0.9994)
            imput = take_profit
            solutions.append(f"Enter long trade {time_stamp}, {imput}")
            
    else:
        take_profit = 0
        imput = imput
        solutions.append("skip investment")

In [85]:
solutions

['Enter short trade, cut off take profit 2023-01-02, 1001.3987999999999',
 'Enter short trade, cut off take profit 2023-01-03, 1002.7995566414398',
 'Enter long trade, cut off take profit 2023-01-04, 1004.2022726612698',
 'Enter short trade, cut off take profit 2023-01-05, 1005.6069508002684',
 'Enter long trade, cut off take profit 2023-01-06, 1007.0135938030478',
 'Enter short trade, cut off take profit 2023-01-07, 1008.4222044180594',
 'Enter short trade 2023-01-08, 1025.1282230199133',
 'Enter short trade 2023-01-09, 1031.7441293266104',
 'Enter short trade, cut off at short stop level 2023-01-10, 1012.717358792191',
 'Enter long trade, cut off take profit 2023-01-11, 1014.1339478336695',
 'Enter short trade, cut off at short stop level 2023-01-12, 991.026898233646',
 'Enter long trade, cut off take profit 2023-01-13, 992.4131466588952',
 'Enter short trade, cut off take profit 2023-01-14, 993.8013341684416',
 'Enter short trade, cut off take profit 2023-01-15, 995.1914634746764',
 'Enter short trade, cut off take profit 2023-01-16, 996.5835372937847',
 'Enter short trade, cut off take profit 2023-01-17, 997.9775583457512',
 'Enter long trade, cut off take profit 2023-01-18, 999.3735293543651',
 'Enter short trade 2023-01-19, 1018.3497569722068',
 'Enter long trade, cut off take profit 2023-01-20, 1019.7742246122594',
 'Enter short trade, cut off take profit 2023-01-21, 1021.200684797647',
 'Enter short trade, cut off take profit 2023-01-22, 1022.6291403155419',
 'Enter short trade, cut off take profit 2023-01-23, 1024.0595939570153',
 'Enter short trade, cut off take profit 2023-01-24, 1025.4920485170423',
 'Enter long trade, cut off take profit 2023-01-25, 1026.926506794508',
 'Enter short trade, cut off take profit 2023-01-26, 1028.362971592212',
 'Enter long trade, cut off take profit 2023-01-27, 1029.8014457168752',
 'Enter short trade, cut off take profit 2023-01-28, 1031.2419319791438',
 'Enter short trade, cut off take profit 2023-01-29, 1032.6844331935963',
 'Enter short trade, cut off take profit 2023-01-30, 1034.1289521787476',
 'Enter short trade, cut off take profit 2023-01-31, 1035.5754917570553',
 'Enter long trade, cut off take profit 2023-02-01, 1037.0240547549251',
 'Enter short trade, cut off take profit 2023-02-02, 1038.4746440027163',
 'Enter long trade, cut off take profit 2023-02-03, 1039.9272623347472',
 'Enter short trade, cut off take profit 2023-02-04, 1041.381912589301',
 'Enter short trade, cut off take profit 2023-02-05, 1042.838597608631',
 'Enter short trade, cut off take profit 2023-02-06, 1044.2973202389658',
 'Enter short trade 2023-02-07, 1069.4702354819783',
 'Enter long trade, cut off take profit 2023-02-08, 1070.9662104473705',
 'Enter short trade, cut off take profit 2023-02-09, 1072.4642779825442',
 'Enter long trade, cut off take profit 2023-02-10, 1073.964441014586',
 'Enter short trade 2023-02-11, 1086.545783116927',
 'Enter short trade, cut off take profit 2023-02-12, 1088.0656433583508',
 'Enter short trade, cut off take profit 2023-02-13, 1089.5876295802805',
 'Enter short trade, cut off take profit 2023-02-14, 1091.1117447565373',
 'Enter long trade, cut off take profit 2023-02-15, 1092.6379918651025',
 'Enter short trade, cut off take profit 2023-02-16, 1094.1663738881234',
 'Enter long trade, cut off take profit 2023-02-17, 1095.696893811918',
 'Enter short trade, cut off take profit 2023-02-18, 1097.2295546269822',
 'Enter short trade, cut off take profit 2023-02-19, 1098.7643593279943',
 'Enter long trade, cut off take profit 2023-02-20, 1100.3013109138221',
 'Enter short trade, cut off take profit 2023-02-21, 1101.8404123875282',
 'Enter long trade 2023-02-22, 1124.1939835558942',
 'Enter short trade, cut off take profit 2023-02-23, 1125.7665061000923',
 'Enter long trade, cut off take profit 2023-02-24, 1127.341228288825',
 'Enter short trade, cut off take profit 2023-02-25, 1128.9181531989555',
 'Enter short trade, cut off take profit 2023-02-26, 1130.4972839116501',
 'Enter short trade, cut off take profit 2023-02-27, 1132.0786235123858',
 'Enter short trade, cut off take profit 2023-02-28, 1133.6621750909549',
 'Enter long trade, cut off take profit 2023-03-01, 1135.247941741472',
 'Enter short trade, cut off take profit 2023-03-02, 1136.8359265623799',
 'Enter long trade, cut off at long stop level 2023-03-03, 1090.7171856669065',
 'Enter long trade, cut off take profit 2023-03-04, 1092.2428808662173',
 'Enter short trade, cut off take profit 2023-03-05, 1093.770710207973',
 'Enter short trade, cut off take profit 2023-03-06, 1095.300676677412',
 'Enter short trade, cut off take profit 2023-03-07, 1096.8327832639482',
 'Enter long trade, cut off take profit 2023-03-08, 1098.3670329611778',
 'Enter short trade, cut off take profit 2023-03-09, 1099.9034287668837',
 'Enter long trade 2023-03-10, 1117.3348895170946',
 'Enter short trade, cut off take profit 2023-03-11, 1118.8978175605512',
 'Enter short trade, cut off take profit 2023-03-12, 1120.4629318277548',
 'Enter short trade, cut off take profit 2023-03-13, 1122.0302353767954',
 'Enter short trade, cut off take profit 2023-03-14, 1123.5997312700406',
 'Enter long trade, cut off take profit 2023-03-15, 1125.1714225741412',
 'Enter short trade, cut off take profit 2023-03-16, 1126.7453123600378',
 'Enter long trade, cut off take profit 2023-03-17, 1128.321403702967',
 'Enter short trade, cut off take profit 2023-03-18, 1129.8996996824667',
 'Enter short trade, cut off take profit 2023-03-19, 1131.4802033823823',
 'Enter short trade, cut off take profit 2023-03-20, 1133.0629178908735',
 'Enter short trade, cut off take profit 2023-03-21, 1134.6478463004191',
 'Enter long trade, cut off take profit 2023-03-22, 1136.234991707824',
 'Enter short trade, cut off take profit 2023-03-23, 1137.8243572142248',
 'Enter long trade, cut off take profit 2023-03-24, 1139.4159459250961',
 'Enter short trade, cut off take profit 2023-03-25, 1141.009760950256',
 'Enter short trade 2023-03-26, 1165.5812318653323',
 'Enter short trade, cut off take profit 2023-03-27, 1167.2116468924655',
 'Enter short trade, cut off take profit 2023-03-28, 1168.8443425441387',
 'Enter long trade, cut off take profit 2023-03-29, 1170.4793220104896',
 'Enter short trade, cut off take profit 2023-03-30, 1172.1165884861177',
 'Enter long trade, cut off take profit 2023-03-31, 1173.7561451700922',
 'Enter short trade, cut off take profit 2023-04-01, 1175.3979952659558',
 'Enter short trade, cut off take profit 2023-04-02, 1177.0421419817337',
 'Enter short trade, cut off take profit 2023-04-03, 1178.6885885299378',
 'Enter short trade, cut off take profit 2023-04-04, 1180.3373381275733',
 'Enter long trade, cut off take profit 2023-04-05, 1181.988393996146',
 'Enter short trade, cut off take profit 2023-04-06, 1183.6417593616677',
 'Enter long trade, cut off take profit 2023-04-07, 1185.2974374546627',
 'Enter short trade 2023-04-08, 1187.5704710702487',
 'Enter short trade, cut off take profit 2023-04-09, 1189.2316446451816',
 'Enter short trade, cut off take profit 2023-04-10, 1190.8951418697113',
 'Enter short trade 2023-04-11, 1218.7054280124114',
 'Enter long trade, cut off take profit 2023-04-12, 1220.4101531651152',
 'Enter short trade 2023-04-13, 1240.526500415878',
 'Enter long trade, cut off take profit 2023-04-14, 1242.2617488846597',
 'Enter short trade, cut off take profit 2023-04-15, 1243.9994246189997',
 'Enter short trade, cut off take profit 2023-04-16, 1245.7395310141567',
 'Enter short trade, cut off take profit 2023-04-17, 1247.4820714701393',
 'Enter short trade, cut off take profit 2023-04-18, 1249.2270493917117',
 'Enter long trade, cut off at long stop level 2023-04-19, 1205.2338898454207',
 'Enter long trade, cut off take profit 2023-04-20, 1206.9197710105364',
 'Enter long trade, cut off take profit 2023-04-21, 1208.608010386226',
 'Enter short trade, cut off take profit 2023-04-22, 1210.2986112711542',
 'Enter short trade, cut off take profit 2023-04-23, 1211.9915769686004',
 'Enter long trade, cut off take profit 2023-04-24, 1213.6869107864638',
 'Enter short trade, cut off take profit 2023-04-25, 1215.384616037272',
 'Enter long trade, cut off take profit 2023-04-26, 1217.0846960381848',
 'Enter long trade, cut off take profit 2023-04-27, 1218.7871541110028',
 'Enter long trade, cut off take profit 2023-04-28, 1220.491993582173',
 'Enter short trade, cut off take profit 2023-04-29, 1222.1992177827958',
 'Enter short trade, cut off take profit 2023-04-30, 1223.9088300486305',
 'Enter short trade, cut off take profit 2023-05-01, 1225.6208337201026',
 'Enter short trade, cut off take profit 2023-05-02, 1227.3352321423101',
 'Enter long trade, cut off take profit 2023-05-03, 1229.0520286650308',
 'Enter short trade, cut off take profit 2023-05-04, 1230.7712266427272',
 'Enter long trade, cut off take profit 2023-05-05, 1232.492829434555',
 'Enter short trade, cut off take profit 2023-05-06, 1234.2168404043682',
 'Enter short trade, cut off take profit 2023-05-07, 1235.9432629207258',
 'Enter short trade, cut off take profit 2023-05-08, 1237.6721003568991',
 'Enter long trade, cut off take profit 2023-05-09, 1239.4033560908783',
 'Enter long trade, cut off take profit 2023-05-10, 1241.1370335053782',
 'Enter short trade, cut off take profit 2023-05-11, 1242.8731359878457',
 'Enter long trade, cut off take profit 2023-05-12, 1244.6116669304654',
 'Enter short trade, cut off take profit 2023-05-13, 1246.3526297301676',
 'Enter short trade, cut off take profit 2023-05-14, 1248.096027788634',
 'Enter short trade, cut off take profit 2023-05-15, 1249.8418645123047',
 'Enter short trade, cut off take profit 2023-05-16, 1251.5901433123845',
 'Enter long trade, cut off take profit 2023-05-17, 1253.3408676048498',
 'Enter short trade, cut off take profit 2023-05-18, 1255.0940408104555',
 'Enter long trade, cut off take profit 2023-05-19, 1256.849666354741',
 'Enter short trade, cut off take profit 2023-05-20, 1258.607747668038',
 'Enter short trade, cut off take profit 2023-05-21, 1260.368288185476',
 'Enter short trade, cut off take profit 2023-05-22, 1262.1312913469899',
 'Enter short trade, cut off take profit 2023-05-23, 1263.896760597326',
 'Enter long trade, cut off at long stop level 2023-05-24, 1221.754069471019',
 'Enter long trade, cut off take profit 2023-05-25, 1223.463059063395',
 'Enter long trade, cut off take profit 2023-05-26, 1225.1744391904128',
 'Enter short trade, cut off take profit 2023-05-27, 1226.8882131959524',
 'Enter short trade, cut off take profit 2023-05-28, 1228.6043844285707',
 'Enter short trade, cut off take profit 2023-05-29, 1230.3229562415095',
 'Enter short trade, cut off take profit 2023-05-30, 1232.0439319927',
 'Enter long trade, cut off take profit 2023-05-31, 1233.7673150447713',
 'Enter short trade, cut off take profit 2023-06-01, 1235.493108765056',
 'Enter long trade, cut off take profit 2023-06-02, 1237.2213165255964',
 'Enter short trade, cut off take profit 2023-06-03, 1238.9519417031522']

In [41]:
print(f"Enter short trade {imput}")

Enter short trade 1175.4401420071652